<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
    <Title>DoubleCorvid's HttpClientHandler</Title>
    <Version>0.16.0-ALPHA</Version>
    <Authors>DoubleCorvid</Authors>
    <Company />
    <Description>A default handler for .Net's HttpClient.</Description>
    <Copyright>Copyright © Raven Crowe 2025</Copyright>
    <PackageProjectUrl>https://github.com/ravencrowe01/DoubleCorvid.HttpClientHandler</PackageProjectUrl>
    <RepositoryUrl>https://github.com/ravencrowe01/DoubleCorvid.HttpClientHandler</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PackageLicenseFile>LICENSE</PackageLicenseFile>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageReleaseNotes>Added CorvidHttpResponse</PackageReleaseNotes>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\LICENSE">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
    <None Include="..\README.md">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Http" Version="9.0.7" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DoubleCorvid.CorvidClientHandler.Framework\DoubleCorvid.CorvidClientHandler.Framework.csproj" />
  </ItemGroup>

</Project>
